---
title: "Elsevier APC Journal List information"
output: github_document
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = TRUE,
  fig.width = 6,
  fig.asp = 0.618,
  out.width = "70%",
  fig.align = "center",
  dpi = 300
)
options(scipen = 999, digits = 4)
knitr::knit_hooks$set(
  inline = function(x) {
    if (is.numeric(x)) {
      return(prettyNum(x, big.mark = ","))
    } else{
      return(x)
    }
  }
)
```

## Portfolio overview

### Load mined data

```{r}
library(tidyverse)
library(here)
els_jns_df <- readr::read_csv(here::here("data", "elsevier_apc_list.csv"))
```

### Journals per business model

```{r}
els_jns_df %>%
  count(oa_type) %>%
  mutate(prop = n / sum(n))
```

### List prices per business model 

Only journals with APC in USD considered

```{r}
els_jns_df %>%
 # filter(apc_currency == "USD") %>%
  group_by(oa_type, apc_currency) %>%
  summarise(n_journals = n(),
            mean_apc = mean(apc, na.rm = TRUE),
            sd = sd(apc, na.rm = TRUE)) %>%
  arrange(desc(apc_currency))
```
```{r}
els_jns_df %>%
  filter(apc_currency == "USD") %>%
  ggplot(aes(oa_type, apc, fill = oa_type)) +
  geom_boxplot() +
  scale_y_continuous(labels = scales::number_format(big.mark = ",")) +
  colorblindr::scale_fill_OkabeIto() +
  cowplot::theme_minimal_hgrid(12) +
  theme(legend.position = "none", 
        plot.title.position = "plot") +
  labs(x = "OA Business Model", y = "APC (in USD)",
       title = "Elsevier APC List Prices by Open Access Business Model",
       caption = "Elsevier: 30 May 2020")
```

## Comparision with Lisa Matthias list

Are both lists equal in terms of hybrid journals?

```{r}
u <- "https://raw.githubusercontent.com/lmatthia/publisher-oa-portfolios/master/elsevier_oa_and_hybrid.csv"
l_apc <- readr::read_delim(u, delim = ";")
l_apc %>%
  filter(year == 2020) %>%
  count(oa_model)
els_hybrid <- els_jns_df %>%
  filter(oa_type == "Hybrid")
l_hybrid <- l_apc %>%
  filter(oa_model == "Hybrid", year == 2020)
base::setequal(els_hybrid$issn, l_hybrid$issn)
```