---
title: "Obtain Article Volume"
author: "Najko Jahn"
date: "7/7/2020"
output: github_document
---

```{r, setup, echo=FALSE, message = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = TRUE,
  fig.width = 6,
  fig.asp = 0.618,
  out.width = "70%",
  fig.align = "center",
  dpi = 300
)
options(scipen = 999, digits = 4)
knitr::knit_hooks$set(
  inline = function(x) {
    if (is.numeric(x)) {
      return(prettyNum(x, big.mark = ","))
    } else{
      return(x)
    }
  }
)
library(tidyverse)
library(here)
```

### Connect to database

```{r}
# connect to google bg where we imported the json lines Unpaywall dump
library(DBI)
library(bigrquery)
con <- dbConnect(
  bigrquery::bigquery(),
  project = "api-project-764811344545",
  dataset = "cr_dump_march_20"
)
```

### Overall article volume per journal and year

```{sql, connection = "con", output.var = "article_volume"}
SELECT issued_year, issn, count(distinct(doi)) as articles
FROM `api-project-764811344545.cr_dump_march_20.els_hybrid_cr`
WHERE issued_year > 2014 and issued_year < 2020
group by issued_year, issn
```

How many articles by year?

```{r}
article_volume %>%
  group_by(issued_year) %>%
  summarise(n = sum(articles))
```

backup

```{r}
write_csv(article_volume, here::here("data", "article_volume.csv"))
```

### Article volume with at least one reference per journal and year

```{sql, connection = "con", output.var = "ref_article_volume"}
SELECT issued_year, issn, count(distinct(doi)) as articles
FROM `api-project-764811344545.cr_dump_march_20.els_hybrid_cr`
WHERE reference_count > 0 AND (issued_year > 2014 and issued_year < 2020)
group by issued_year, issn
```

```{r}
ref_article_volume %>%
  group_by(issued_year) %>%
  summarise(n = sum(articles))
```

backup

```{r}
write_csv(ref_article_volume, here::here("data", "ref_article_volume.csv"))
```

### Validation: Do these journals actually deposit references with Crossref

```{r}
zero_ref_jns <- article_volume %>% 
  filter(!issn %in% ref_article_volume$issn) %>% 
  distinct(issn)
```

Do these journals deposit references?

```{r}
library(rcrossref)
cr_jns <- rcrossref::cr_journals(zero_ref_jns$issn)
table(current = cr_jns$data$deposits_references_current, back_file =  cr_jns$data$deposits_references_backfile)
```

All journals deposited references with Crossref!