---
output: github_document
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 6,
  fig.asp = 0.618,
  out.width = "70%",
  fig.align = "center",
  dpi = 300
)
options(scipen = 999, digits = 4)
knitr::knit_hooks$set(
  inline = function(x) {
    if (is.numeric(x)) {
      return(formatC(x, big.mark = ",", format = "fg", digits = 2))
    } else{
      return(x)
    }
  }
)
```

```{r}
# libraries
library(tidyverse)
library(here)
library(cowplot)
library(gt)
library(janitor)
```

```{r}
hybrid_volume <- readr::read_csv(here::here("data", "hybrid_volume_eligible.csv"))
```

```{r}
ind_per_jn <- hybrid_volume %>%
  group_by(issn, container_title, articles, issued_year) %>%
  summarise(n = n_distinct(doi)) %>%
  mutate(prop = n / articles)
```

read in scopus journal indicators

```{r}
scopus_19 <- readxl::read_excel(here::here("data", "scopus_jn.xlsx"), sheet = 2,
                                .name_repair = make_clean_names)
```

normalize scopus jn indicators

```{r}
scopus_norm <- scopus_19 %>%
  gather(print_issn, e_issn, key = "issn_tpye", value = "issn") %>%
  # trailing zero's missing in Excel spreadsheet
  mutate(
    issn = ifelse(nchar(issn) == 5, paste0("000", issn), issn),
    issn = ifelse(nchar(issn) == 6, paste0("00", issn), issn),
    issn = ifelse(nchar(issn) == 7, paste0("0", issn), issn)) %>%
  # missing hyphen
  mutate(issn = map_chr(issn, function(x) paste(c(substr(x, 1, 4), substr(x, 5, 8)), collapse = "-")))
```

missing journals (needs to be validated)

```{r}
hybrid_volume %>% 
  filter(!issn %in% scopus_norm$issn) %>% 
  distinct(issn, container_title)
```

backup

```{r}
cite_score_19 <- scopus_norm %>% 
  select(issn, contains("subject"), percentile, snip, sjr)
write_csv(cite_score_19, here::here("data", "cite_score_19.csv"))
```

```{r}
ajsc_mapped <- read_csv(here::here("data", "asjc_mapped.csv")) %>%
  mutate(top_level_code = as.character(top_level_code))
hybrid_subject <- left_join(ind_per_jn, cite_score_19, by = c("issn" = "issn")) %>%
  mutate(top_level_code = substr(as.character(scopus_asjc_code_sub_subject_area), 1, 2)) %>%
  inner_join(ajsc_mapped, by = "top_level_code")
# backup subject liste
hybrid_subject %>% 
  ungroup() %>% 
  distinct(issn, container_title, subject_area, top_level = description) %>%
  write_csv(here::here("data", "jn_subjects.csv"))
```

### Correlation test

```{r}
hybrid_subject_19 <- hybrid_subject %>% 
  filter(issued_year == "2019", !is.na(percentile)
         #, prop > 0.01 & prop < 0.15) 
         )%>%
  distinct(issn, prop, percentile, snip, sjr)
```

spearman

```{r}
cor.test(hybrid_subject_19$prop, hybrid_subject_19$percentile, method = "spearman")
```

plot
```{r}
ggplot(hybrid_subject_19, aes(prop, percentile)) + geom_point(alpha = .3) + geom_smooth(method = "lm") +
  coord_cartesian(xlim = c(0.01, 0.5), ylim = c(0,100))
```

- cell system, global food security

```{r}
hybrid_subject %>%
  filter(issued_year == "2019", !is.na(percentile)) %>% 
  ggplot(aes(prop, percentile)) + geom_point(alpha = .3) + geom_smooth(method = "lm") +
  facet_wrap(~top_level_code) +
  coord_cartesian(xlim = c(0.01, 0.5), ylim = c(0,100))
```

## OA proportion per subject

```{r}
# sort by median per asjc subject group
subject_all_years <- hybrid_subject %>% 
  ungroup() %>% 
  group_by(issn, description, subject_area) %>% 
  summarise(n_oa = sum(n),
            n = sum(articles)) %>%
  ungroup() %>%
  group_by(description) %>%
  filter(subject_area != "Multidisciplinary")

ggplot(subject_all_years, aes(fct_reorder(description, n / n_oa, .fun = median, .desc = TRUE), n_oa / n)) + 
  geom_boxplot(aes(color = subject_area)) +
  geom_jitter(alpha = .05, aes(color = subject_area)) +
  coord_flip() +
  coord_cartesian()
  scale_colour_manual(values = c("#7F3C8D", "#11A579", "#3969AC", "#F2B701")) +
  scale_y_continuous(
    labels = scales::percent_format(accuracy = 5L),
    expand = expansion(mult = c(0, 0.05))
  ) +
  labs(x = NULL, y = "Five-Years OA Uptake Rate per Journal") +
  theme_minimal_vgrid()
```
- Comptes Rendus https://www.library.illinois.edu/mtx/2020/05/01/comptes-rendus-de-lacademie-des-sciences-important-publishing-and-access-changes/

### by funder

```{r}
jn_subjects <- read_csv(here::here("data", "jn_subjects.csv"))

hybrid_volume_subjects <- hybrid_volume %>%
  group_by(oa_sponsor_type, articles, issued_year, issn) %>% 
  summarise(n_oa = n_distinct(doi)) %>% 
  left_join(jn_subjects, by = "issn") %>%
  ungroup()

hybrid_volume_subjects %>%
 # filter(container_title == "Journal of the American College of Cardiology") %>%
  group_by(top_level, articles, issued_year) %>%
  summarise(n_oa = sum(n_oa)) %>%
  ungroup() %>%
  group_by(top_level) %>%
  summarise(n_oa = sum(n_oa),
            n = sum(articles), .groups = "drop") %>%
  mutate(prop = n_oa / n) %>%
  arrange(desc(prop))
  

hybrid_volume %>%
  left_join(jn_subjects, by = "issn") %>%
  group_by(oa_sponsor_type, issn, issued_year, top_level, articles) %>%
  summarise(n_oa = n_distinct(doi)) %>%
  group_by(oa_sponsor_type, issued_year, top_level) %>%
  summarise(n_oa = sum(n_oa),
            n = sum(articles)) %>%
  ungroup() %>%
  group_by(top_level, oa_sponsor_type) %>%
  summarise(n_oa = sum(n_oa, na.rm = TRUE),
            n = sum(n, na.rm = TRUE)) %>%
  mutate(prop = n_oa / n) %>% View()


hybrid_volume %>%
  left_join(jn_subjects, by = "issn") %>%
  group_by(issn, issued_year, top_level, article) %>%
  summarise(n_oa = n_distinct(doi)) %>%
  group_by(issued_year, top_level) %>%
  summarise(nn = sum(n_oa))
```